version: "3.8"

services:

    data:
        container_name: sqlserver
        image: mcr.microsoft.com/azure-sql-edge:latest
        ports: 
            - "1433:1433"
        environment:
            - ACCEPT_EULA=Y
            - MSSQL_SA_PASSWORD=yourStrongPassword12!@
        volumes: 
            - events_mssql:/var/opt/mssql
            - ./setup.sql:/usr/config/setup.sql
        networks: 
            - pizza-network

    server:
        container_name: server
        image: ivaylodoynov/pizza-server:1.0
        build:
            context: ./Server
            dockerfile: ./Pizzeria.Server/Dockerfile
        ports: 
            - "5001:80"
        env_file: 
            - Server/Pizzeria.Server/Common.env
        restart: on-failure
        volumes:
            - ./.aspnet/DataProtection-Keys:/root/.aspnet/DataProtection-Keys
        networks: 
            - pizza-network
        depends_on:
            - data

    client:
        container_name: client
        image: ivaylodoynov/pizza-user-client:1.0
        build:
            context: ./Client
            dockerfile: ./Dockerfile
        ports: 
            - "80:80"
        restart: on-failure
        depends_on:
            - server

networks:
    pizza-network:

volumes:
    events_mssql:
